[versions]
awaitility = "4.2.2"
commonsLang = "3.17.0"
hivemq-extensionSdk = "4.3.0"
hivemq-mqttClient = "1.3.3"
jaxb-api = "4.0.2"
jaxb-impl = "4.0.5"
jetbrains-annotations = "24.1.0"
junit-jupiter = "5.10.3"
logback = "1.5.8"
mockito = "5.14.1"
okhttp = "4.12.0"
testcontainers = "1.20.2"

[libraries]
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
commonsLang = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang" }
hivemq-mqttClient = { module = "com.hivemq:hivemq-mqtt-client", version.ref = "hivemq-mqttClient" }
jaxb-api = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jaxb-api" }
jaxb-impl = { module = "org.glassfish.jaxb:jaxb-runtime", version.ref = "jaxb-impl" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
testcontainers-hivemq = { module = "org.testcontainers:hivemq", version.ref = "testcontainers" }
testcontainers-junitJupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }

[plugins]
hivemq-extension = { id = "com.hivemq.extension", version = "3.2.0" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
license = { id = "com.github.hierynomus.license", version = "0.16.1" }
